import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { ThemeProvider } from "next-themes"
import StoreProvider from "./storeProvider";
import { Toaster } from "sonner";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-h-screen flex flex-col">
                <StoreProvider>
                    <Navbar />
                    <main className="grow container mx-auto px-4 py-8">
                        {children}
                    </main>

                    <Footer />
                </StoreProvider>
                <Toaster position="top-right" richColors />
            </body>
        </html>
    );
}
